"""creates the customers table

Revision ID: c3ef1ffd485d
Revises: 
Create Date: 2023-01-17 17:11:42.866000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ef1ffd485d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=True),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('postal_code', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contact_name'), ['contact_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_name'), ['customer_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_contact_name'))

    op.drop_table('customer')
    # ### end Alembic commands ###
